name: build-test-deploy_environment

on:
  workflow_dispatch:

env:
    # Set the Node Version
    NODE_VERSION: '18.x'

jobs:
  install-build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'

    - name: Install, build, test
      run: |
        npm ci
        npm run build --if-present
        npm test

  stage_deploy:
    runs-on: ubuntu-latest
    needs: install-build-test
    environment:
      name: staging

    steps:
      # Simulate a deployment
      - name: Deploy to Staging
        run: |
          echo "Deployed to staging environment"

  production_deploy:
    runs-on: ubuntu-latest
    needs: stage_deploy
    environment:
      name: production

    steps:
      # Simulate a deployment
      - name: Deploy to production
        run: |
          echo "Deployed to production environment"
        

      












# #AWSTemplateFormatVersion: 2010-09-09
# Description: Create an S3 bucket
# Resources:
#   UdaBucket:
#     Type: AWS::S3::Bucket
#     Properties:
#       BucketName: uda-iye-bucket
#       WebsiteConfiguration:
#         IndexDocument: index.html
#         ErrorDocument: error.html
# Outputs:
#   WebsiteURL:
#     Value: !GetAtt UdaBucket.WebsiteURL
#     Description: URL for website hosted on S3
#   S3BucketSecureURL:
#     Value: !GetAtt UdaBucket.DomainName
#     Description: Name of S3 bucket to hold website content
  